### ISSUE TITLE
docs: apinto-dashboard 新建api分组后无法使用

### ISSUE THREAD

**Issue by jober2014** [eolinker/apinto-dashboard#15]
### Current State

dashboard 新建
![QQ截图20230324110551](https://user-images.githubusercontent.com/9709795/227413998-1b0d9b0a-1f3f-452a-bc1c-a6a083d918e6.png)
api分组后，在新建api下拉列表中，依然没有下拉分组数据。无法保存api
![QQ截图20230324110638](https://user-images.githubusercontent.com/9709795/227414107-e44ce221-2c94-48b7-aacb-70a8653d592e.png)

### Desired State

分组数据下拉列表应该有数据，才能成功保存API

**Comment by Dot-Liu** [comment]
产品设计是，新建了分组后，还需要再新建子分组，才能加接口
一级分组定义为项目层级
二级分组定义为业务模块

**Comment by jober2014** [comment]
为什么我配制了路由转发不成功？



接口地址是没问题的：







修仙者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eolinker/apinto-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eolinker/apinto-dashboard] docs: apinto-dashboard 新建api分组后无法使用 (Issue #15)





 
产品设计是，新建了分组后，还需要再新建子分组，才能加接口
 一级分组定义为项目层级
 二级分组定义为业务模块

**Comment by Dot-Liu** [comment]
我看您是已经加入到我们的用户群了    我将关闭该issue    使用上的可以在群里进行咨询

**Comment by jober2014** [comment]
好的&nbsp;


修仙者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eolinker/apinto-dashboard] docs: apinto-dashboard 新建api分组后无法使用 (Issue #15)





 
我看您是已经加入到我们的用户群了    我将关闭该issue    使用上的可以在群里进行咨询
