### ISSUE TITLE
bug: Dont Work Dashboard In Docker

### ISSUE THREAD

**Issue by max-dicson-cf** [eolinker/apinto-dashboard#20]
### Current Behavior

Hello,
I have currently installed on a cloud server:

- https://github.com/eolinker/apinto (command line)
- https://github.com/eolinker/apinto-dashboard (docker-compose)

However, I encounter an error when trying to access the following route.: http://localhost:18080/login

![image](https://github.com/eolinker/apinto-dashboard/assets/5543144/8dc12bef-359f-4355-9a4f-bd8a0c56c3a0)

The YAML file for deployment is as follows:

`version: '3'
services:
  mysql:
    image: mysql:5.7.34
    privileged: true
    restart: always
    container_name: apinto_mysql
    hostname: apinto_mysql
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=apinto
    volumes:
      - /var/lib/apinto/mysql:/var/lib/mysql
    networks:
      - apinto
  apinto-dashboard:
    image: eolinker/apinto-dashboard
    container_name: apinto-dashboard
    privileged: true
    restart: always
    networks:
      - apinto
    ports:
      - "18080:8080"
    depends_on:
      - mysql
      - redis_cluster
    environment:
      - MYSQL_USER_NAME=root
      - MYSQL_PWD=123456
      - MYSQL_IP=apinto_mysql
      - MYSQL_PORT=3306                 #mysql端口
      - MYSQL_DB="apinto"
      - ERROR_DIR=/apinto-dashboard/work/logs  # 日志放置目录
      - ERROR_FILE_NAME=error.log          # 错误日志文件名
      - ERROR_LOG_LEVEL=info               # 错误日志等级,可选:panic,fatal,error,warning,info,debug,trace 不填或者非法则为info
      - ERROR_EXPIRE=7d                    # 错误日志过期时间，默认单位为天，d|天，h|小时, 不合法配置默认为7d
      - ERROR_PERIOD=day                  # 错误日志切割周期，仅支持day、hour
      - REDIS_ADDR=172.100.0.1:7201,172.100.0.1:7202,172.100.0.1:7203,172.100.0.1:7204,172.100.0.1:7205,172.100.0.1:7206 #Redis集群地址 多个用,隔开
      - REDIS_PWD=123456                         # Redis密码
    volumes:
      - /var/log/apinto/apinto-dashboard/work:/apinto-dashboard/work   #挂载log到主机目录
  redis_cluster:
    container_name: redis_cluster
    image: eolinker/cluster-redis:6.2.7
    hostname: redis_cluster
    privileged: true
    restart: always
    environment:
      - REDIS_PWD=123456
      - PORT=7201
      - HOST=172.18.21.251
    volumes: 
      - /var/lib/apinto/redis-cluster/data:/usr/local/cluster_redis/data
    network_mode: host
networks:
  apinto:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24`

I can't find where I should configure the Apinto services like the IP addresses of the clusters. What could be the issue?

### Expected Behavior

I would expect to see what is shown in the image, which I extracted from this repository.

![image](https://github.com/eolinker/apinto-dashboard/assets/5543144/1e9d1ff6-0835-455f-acfe-8475a2008a2f)

### Steps to Reproduce

1. Install apinto by command line
2. Install apinto-dashboard by docker-compose

### Environment

- APINTO Dashboard version (run `apinto dashboard version`):
- Operating system (run `uname -a`):

**Comment by Dot-Liu** [comment]
run this command:
`docker restart apinto-dashboard`

**Comment by Dot-Liu** [comment]
May I ask if the problem has been resolved? If so, I will close the issue.
