### ISSUE TITLE
日志检索中的追踪日志不可用

### ISSUE THREAD

**Issue by TsangBill** [eolinker/apinto-dashboard#24]
### Current Behavior

追踪日志不能实时获取数据，连接IP似乎是没有取真实地址。

### Error Logs

![image](https://github.com/eolinker/apinto-dashboard/assets/31025761/9c4b66ea-0988-4c8d-8be6-308070c03660)

### Steps to Reproduce

1. 进入后台打开“日志检索”
2. 在浏览器中F12打开开发工具，选择“Console”
3. 在“日志详情” 点击 “节点日志”，并观察“Console”中日志

### Environment

- APINTO Dashboard version (run `apinto dashboard version`):apserver_v3.2.1
- Operating system (run `uname -a`):Linux test 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hmzzrcs** [comment]
node日志需要配置 ouoput为file的access-log插件

**Comment by hmzzrcs** [comment]
1 这个 ip 是和openapi是同一个ip,
2. apinto的版本需要 v0.13.2 以上

**Comment by TsangBill** [comment]
> 1 这个 ip 是和openapi是同一个ip, 2. apinto的版本需要 v0.13.2 以上

版本已经是0.14.5了 
![image](https://github.com/eolinker/apinto-dashboard/assets/31025761/9f0a5b2f-8c3b-4ee5-a5dc-c508d5581a03)

**Comment by hmzzrcs** [comment]
> > 1 这个 ip 是和openapi是同一个ip, 2. apinto的版本需要 v0.13.2 以上
> 
> 版本已经是0.14.5了 ![image](https://user-images.githubusercontent.com/31025761/269807978-9f0a5b2f-8c3b-4ee5-a5dc-c508d5581a03.png)

你这个是从哪里访问的, 官方demo环境吗, 官方的demo环境没有开放apinto的admin 端口出来, 必须是你自己的网络能访问apinto才行

**Comment by hmzzrcs** [comment]
sorry, 刚刚让前端确认了一下, 是前端的bug,

**Comment by Dot-Liu** [comment]
该问题已经修复，请更新到最新版本的控制台

**Comment by Dot-Liu** [comment]
我将关闭该issue，感谢您的反馈
