### ISSUE TITLE
bug:  上游菜单中的页面数据缺失

### ISSUE THREAD

**Issue by zxzixuanwang** [eolinker/apinto-dashboard#32]
### Current Behavior

点开上游的页面，就能发现只有15条数据，前端按照20条进行分页查询，但是后端只有15条返回，导致缺失5条

### Steps to Reproduce

接口： /api/dynamic/upstream/list?page=1&pageSize=20&keyword=&cluster=%5B%5D&namespace=default
此带有dynamic 的请求在api.service.ts underline() 方法中，忽略了驼峰转下划线的转换
后端中，modules/dynamic/dynamic-controller./dynamic.go 获取getPage()  为 pageSize := ctx.Query("page_size")，全局搜索到，后端基本没有pageSize的query 参数获取了。

### Environment

- APINTO Dashboard version (run `apinto dashboard version`): v3.3.3
- Operating system (run `uname -a`): 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux

**Comment by hmzzrcs** [comment]
已解决
