### ISSUE TITLE
feat: 广告越来越多了

### ISSUE THREAD

**Issue by ylwind** [eolinker/apinto-dashboard#33]
### Description

理解apinto作为开源项目，需要为自己的pro版本引流。但是在最新的3.2.2版本中，内嵌了api市场以及众多的广告按钮。
想提个小建议，能否减少开源版中的引流呢

**Comment by Dot-Liu** [comment]
有些用户需要所以我们才做的，您不需要就停用相关插件即可

**Comment by ylwind** [comment]
好的，我探索下，我先关闭issue了哈～
