### ISSUE TITLE
sqlite支持库修改建议

### ISSUE THREAD

**Issue by yanjunhui** [eolinker/apinto-dashboard#5]
### Description

目前使用的包为 github.com/mattn/go-sqlite3 不支持跨平台编译
建议替换成 modernc.org/sqlite  
仅供参考

**Comment by Dot-Liu** [comment]
感谢反馈。 验证完成后进行替换。 稍作等待

**Comment by Dot-Liu** [comment]
已经修改完成，感谢建议
