### ISSUE TITLE
build报错，找不到tpl模板

### ISSUE THREAD

**Issue by lsx08** [eolinker/apinto-dashboard#9]
### Current Behavior

![image](https://user-images.githubusercontent.com/10581852/205214966-c4104a77-7e41-4eaa-9a06-fa6233f40c84.png)
如图，build.sh里面这句话找不到模板文件，修改为：cp -a ${BasePath}/internal/template/tpl ${OUTPATH}/
可以正常打包

### Expected Behavior

修订问题

### Steps to Reproduce

按照官方打包教程打包就会报错

### Environment

main分支

**Comment by Dot-Liu** [comment]
的确是的，在最新版本的打包中，不需要这个tpl目录了，这个报错不影响打包
您可以删除tpl的命令，再build

**Comment by lsx08** [comment]
好的，感谢
